<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-ScoringWorker-30699871-8179-418d-8aad-5621283276aa</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit.AspNetCore" Version="9.2.0-develop.155" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.0-develop.155" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.17"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Consumers\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Data\Data.csproj" />
    </ItemGroup>
</Project>
