<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-ScoringWorker-30699871-8179-418d-8aad-5621283276aa</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.3.6" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.17"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Data\Data.csproj" />
      <ProjectReference Include="..\..\MatchDataIngestion\MatchDataIngestion\MatchDataIngestion.csproj" />
    </ItemGroup>
</Project>
