// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729122229_AddUserRelationToSquad")]
    partial class AddUserRelationToSquad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.DomainModels.Fixture", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("assist_player_id")
                        .HasColumnType("text");

                    b.Property<string>("match_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("minute")
                        .HasColumnType("integer");

                    b.Property<string>("player_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("team_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("Shared.DomainModels.Match", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("away_team_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("gameweek")
                        .HasColumnType("integer");

                    b.Property<string>("home_team_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("kickoff")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("minute")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Shared.DomainModels.Player", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("price")
                        .HasColumnType("numeric");

                    b.Property<string>("team_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("total_points")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Shared.DomainModels.Squad", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SquadName")
                        .HasColumnType("text");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer");

                    b.Property<int>("gameweek")
                        .HasColumnType("integer");

                    b.Property<string>("user_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("Squads");
                });

            modelBuilder.Entity("Shared.DomainModels.SquadPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Multiplier")
                        .HasColumnType("integer");

                    b.Property<string>("SquadId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_bench")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_captain")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_vice_captain")
                        .HasColumnType("boolean");

                    b.Property<string>("player_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("position_slot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SquadId");

                    b.ToTable("SquadPlayers");
                });

            modelBuilder.Entity("Shared.DomainModels.Team", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("Short")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("stadium")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Shared.DomainModels.User", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("league_id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("total_points")
                        .HasColumnType("integer");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shared.DomainModels.Match", b =>
                {
                    b.OwnsOne("Shared.DomainModels.MatchScore", "Score", b1 =>
                        {
                            b1.Property<string>("Matchid")
                                .HasColumnType("text");

                            b1.Property<int>("away")
                                .HasColumnType("integer");

                            b1.Property<int>("home")
                                .HasColumnType("integer");

                            b1.HasKey("Matchid");

                            b1.ToTable("Matches");

                            b1.WithOwner()
                                .HasForeignKey("Matchid");
                        });

                    b.Navigation("Score");
                });

            modelBuilder.Entity("Shared.DomainModels.Player", b =>
                {
                    b.OwnsOne("Shared.DomainModels.PlayerStats", "stats", b1 =>
                        {
                            b1.Property<string>("Playerid")
                                .HasColumnType("text");

                            b1.Property<int>("assists")
                                .HasColumnType("integer");

                            b1.Property<int>("clean_sheets")
                                .HasColumnType("integer");

                            b1.Property<int>("goals")
                                .HasColumnType("integer");

                            b1.Property<int>("minutes_played")
                                .HasColumnType("integer");

                            b1.Property<int>("own_goals")
                                .HasColumnType("integer");

                            b1.Property<int>("penalties_missed")
                                .HasColumnType("integer");

                            b1.Property<int>("red_cards")
                                .HasColumnType("integer");

                            b1.Property<int>("saves")
                                .HasColumnType("integer");

                            b1.Property<int>("yellow_cards")
                                .HasColumnType("integer");

                            b1.HasKey("Playerid");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("Playerid");
                        });

                    b.Navigation("stats")
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.DomainModels.Squad", b =>
                {
                    b.HasOne("Shared.DomainModels.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.DomainModels.SquadPlayer", b =>
                {
                    b.HasOne("Shared.DomainModels.Squad", null)
                        .WithMany("Players")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.DomainModels.Squad", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
