<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-LeaderboardWorker-c43a1cae-a71d-4c84-ae83-7e386e52eccf</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit.AspNetCore" Version="9.2.0-develop.155" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.0-develop.155" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.17"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Consumers\" />
    </ItemGroup>
</Project>
