<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-MatchDataIngestion-7aea3d76-687c-4807-a223-f1c44b33fe17</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.3.6" />
        <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.3.6" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.1" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup>
        <!-- Root'a girer-->
        <None Include="..\..\..\mock-data\**\*">
            <Link>mock-data\%(RecursiveDir)%(FileName)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\..\Data\Data.csproj" />
    </ItemGroup>
</Project>
